name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
      
    - name: Create env file
      run: |
        touch .env
        echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env 
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env 
        echo "GUILD_ID=${{ secrets.GUILD_ID }}" >> .env 
        echo "NEFA_ID=${{ secrets.NEFA_ID }}" >> .env 
        echo "ESPRIT_ID=${{ secrets.ESPRIT_ID }}" >> .env 
        echo "MINIBABYMEL_ID=${{ secrets.MINIBABYMEL_ID }}" >> .env 
        echo "PATON_ID=${{ secrets.PATON_ID }}" >> .env 
        echo "PUMPKIN_ID=${{ secrets.PUMPKIN_ID }}" >> .env 
        echo "GOUPIL_ID=${{ secrets.GOUPIL_ID }}" >> .env 
        echo "MONO_ID=${{ secrets.MONO_ID }}" >> .env 
        cat .env

    - name: Create JSON config file
      run: |
        touch config.json
        echo "{ clientId=${{ secrets.CLIENT_ID }} guildId=${{ secrets.GUILD_ID }} token=${{ secrets.DISCORD_TOKEN }} }" >> config.json 
        cat config.json

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - uses: actions/checkout@v1

    - name: Login to Heroku Container registry
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login 

    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a fdn-melvina-bot web 
